### ISSUE TITLE
module 'fafbseg.flywire' has no attribute 'set_default_dataset'

### ISSUE THREAD

**Issue by dustingarner** [navis-org/fafbseg-py#14]
According to the documentation, setting the dataset to public requires fafbseg.set_default_dataset("public"). However, when I run it, I receive the error: module 'fafbseg.flywire' has no attribute 'set_default_dataset'. Here is my code:

`from fafbseg import flywire`
`flywire.set_default_dataset("public")`

**Comment by schlegelp** [comment]
Hi Dustin. This function is a recent addition. What version of `fafbseg` are you using?

```python
import fafbseg
print(fafbseg.__version__)
```

**Comment by dustingarner** [comment]
Hi Philipp, that was the issue. I believe my IDE was running the wrong virtual environment and it was using an older version of `fafbeg`. Thank you for the help.
