### ISSUE TITLE
minimum python version is now >=3.7.1

### ISSUE THREAD

**Issue by jefferis** [navis-org/fafbseg-py#6]
was trying to install under python 3.6 but pandas >=1.2.0 => python >=3.7.1 https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.2.0.html#increased-minimum-version-for-python

**Comment by schlegelp** [comment]
Ah, thanks for pointing that out - I wasn't aware of that. Do you still need it to work with Python 3.6? If so, I could probably safely lower the pandas requirement to `>=1.1.0`.

**Comment by jefferis** [comment]
Thank! If you don't insist on that pandas version, it would be nice as the stock environment under reticulate is still 3.6.0 and it requires some mucking around e.g. to get a 3.8.0 environment. I've done it, but I wouldn't really encourage habitual nat end users to do the same.

**Comment by schlegelp** [comment]
f2b4565c7e0d205612ab80f070e22d298ad45c39 lowers the requirements for pandas to >=1.1.0 
I don't anticipate any issues but I also haven't done much testing. Let me know if there are any unforeseen issues.

I'd be surprised if reticulate didn't upgrade to 3.7 soon as 3.6 has reached its EOL in December.

**Comment by jefferis** [comment]
Thanks! Turns out it's already 3.8 in dev https://github.com/rstudio/reticulate/pull/1094
